// @awa-component: PLAN-017-BitmarkJsonSchema
import * as monaco from 'monaco-editor';

import { log } from '../logging/log';

/**
 * The parser publishes a JSON Schema of its own output beside the engine
 * (`schema/bitmark.schema.json`, generated by `bitmark-schemagen`). Binding it
 * to Monaco's JSON language service gives the JSON pane the same three things
 * the bitmark pane gets from the parser — validation, completion and hover —
 * with no parser call at all, and from the SAME version as the engine.
 */
export const BITMARK_SCHEMA_URI = 'https://getmorebrain.github.io/bitmark/bitmark.schema.json';

/** The schema URL beside an engine URL (`…/dist/browser/x.js` → `…/schema/…`). */
export const schemaUrlFor = (engineUrl: string): string => {
  const clean = engineUrl.split('?')[0];
  if (clean.includes('/dist/browser/')) {
    return `${clean.split('/dist/browser/')[0]}/schema/bitmark.schema.json`;
  }
  // The local-engine route serves the package's own directories.
  return `${clean.replace(/[^/]*$/, '')}schema.json`;
};

/**
 * Fetch the schema and hand it to Monaco's JSON worker. Applies to every JSON
 * model in the app — the bit-JSON pane and the JSON diff, both of which hold
 * a bitmark document. Failure is silent: the pane then validates JSON syntax
 * only, exactly as before.
 */
export const registerBitmarkJsonSchema = async (engineUrl: string): Promise<boolean> => {
  try {
    const response = await fetch(schemaUrlFor(engineUrl));
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const schema = (await response.json()) as unknown;
    monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
      validate: true,
      allowComments: false,
      enableSchemaRequest: false,
      schemas: [{ uri: BITMARK_SCHEMA_URI, fileMatch: ['*'], schema }],
    });
    return true;
  } catch (e) {
    log.warn('bitmark JSON schema not loaded; the JSON pane checks syntax only', e);
    return false;
  }
};
